const teams = [{
  name: '纽约尼克斯 (New York Knicks)',
  abbreviation: '尼克斯',
  city: '纽约州 纽约市',
  latlng: '40.750623, -73.993440',
  side: '东部联盟',
  division: '大西洋赛区',
  arena: '麦迪逊广场花园(Madison Square Garden)',
}, {
  name: '波士顿凯尔特人 (Boston Celtics)',
  abbreviation: '凯尔特人',
  city: '马萨诸塞洲 波士顿市',
  latlng: '42.366269, -71.062392',
  side: '东部联盟',
  division: '大西洋赛区',
  arena: 'TD北岸花园中心球馆（TD Garden）',
}, {
  name: '费城76人 (Philadelphia 76ers)',
  abbreviation: '76人',
  city: '宾夕法尼亚州 费城市',
  latlng: '39.969717, -75.161976',
  side: '东部联盟',
  division: '大西洋赛区',
  arena: '瓦乔维亚中心球场(Wachovia Center)',
}, {
  name: '多伦多猛龙 (Toronto Raptors)',
  abbreviation: '猛龙',
  city: '加拿大 多伦多市',
  latlng: '43.643115, -79.378433',
  side: '东部联盟',
  division: '大西洋赛区',
  arena: '加拿大航线中心体育馆(Air Canada Centre)',
}, {
  name: '布鲁克林篮网',
  abbreviation: '篮网',
  city: '纽约',
  latlng: '40.682601, -73.975381',
  side: '东部联盟',
  division: '大西洋赛区',
  arena: '巴克莱中心',
}, {
  name: '克里夫兰骑士 (Cleveland Cavaliers)',
  abbreviation: '骑士',
  city: '俄亥俄州 克里夫兰市',
  latlng: '41.496431, -81.688363',
  side: '东部联盟',
  division: '中部赛区',
  arena: '冈德体育馆(Gund Arena)',
}, {
  name: '印地安纳步行者 (Indiana Pacers)',
  abbreviation: '步行者',
  city: '印第安纳州 印第安纳波利斯市',
  latlng: '39.763673, -86.155255',
  side: '东部联盟',
  division: '中部赛区',
  arena: '班克斯人寿球馆(Bankers Life Fieldhouse)',
}, {
  name: '底特律活塞 (Detroit Pistons)',
  abbreviation: '活塞',
  city: '密歇根州 底特律市',
  latlng: '42.697039, -83.245152',
  side: '东部联盟',
  division: '中部赛区',
  arena: '奥本山宫殿球场(The Palace of Auburn Hills)',
}, {
  name: '密尔沃基雄鹿 (Milwaukee Bucks)',
  abbreviation: '雄鹿',
  city: '威斯康星州 密尔沃基市',
  latlng: '43.043597, -87.917074',
  side: '东部联盟',
  division: '中部赛区',
  arena: '布拉德利中心(Bradley Center)',
}, {
  name: '芝加哥公牛 (Chicago Bulls)',
  abbreviation: '公牛',
  city: '伊利诺斯州 芝加哥市',
  latlng: '41.880683, -87.674026',
  side: '东部联盟',
  division: '中部赛区',
  arena: '联合中心球馆(United Center)',
}, {
  name: '华盛顿奇才 (Washington Wizards)',
  abbreviation: '奇才',
  city: '华盛顿特区 华盛顿',
  latlng: '38.898083, -77.021062',
  side: '东部联盟',
  division: '东南赛区',
  arena: 'MIC中心球馆(MCI Centre)',
}, {
  name: '奥兰多魔术 (Orlando Magics)',
  abbreviation: '魔术',
  city: '佛罗里达州 奥兰多市',
  latlng: '45.498123, -73.566569',
  side: '东部联盟',
  division: '东南赛区',
  arena: '水屋中心体育馆(TD Waterhouse Center)',
}, {
  name: '迈阿密热火 (Miami Heats)',
  abbreviation: '热火',
  city: '佛罗里达州 迈阿密市',
  latlng: '25.781292, -80.187782',
  side: '东部联盟',
  division: '东南赛区',
  arena: '美航球馆(American Airlines Arena)',
}, {
  name: '夏洛特黄蜂',
  abbreviation: '黄蜂',
  city: '北卡罗莱纳州 夏洛特市',
  latlng: '35.225046, -80.839224',
  side: '东部联盟',
  division: '东南赛区',
  arena: '：夏洛特球馆(Charlotte Arena)',
}, {
  name: '亚特兰大老鹰 (Atlanta Hawks)',
  abbreviation: '老鹰',
  city: '乔治亚州 亚特兰大市',
  latlng: '33.757209, -84.396378',
  side: '东部联盟',
  division: '东南赛区',
  arena: '菲利浦斯球馆(Philips Arena)',
}, {
  name: '俄克拉荷马雷霆 (Oklahoma City Thunder)',
  abbreviation: '雷霆',
  city: '俄克拉荷马',
  latlng: '33.110794, -96.827794',
  side: '西部联盟',
  division: '西北赛区',
  arena: '福特中心球场(Ford Center)',
}, {
  name: '明尼苏达森林狼 (Minnesota Timberwolves)',
  abbreviation: '森林狼',
  city: '明尼苏达 明尼阿波利斯',
  latlng: '44.979444, -93.276096',
  side: '西部联盟',
  division: '西北赛区',
  arena: '目标中心球馆(Target Center)',
}, {
  name: '丹佛掘金 (Denver Nuggets)',
  abbreviation: '掘金',
  city: '科多拉多州 丹佛市',
  latlng: '39.748602, -105.007345',
  side: '西部联盟',
  division: '西北赛区',
  arena: '百事中心球馆(Pepsi Center)',
}, {
  name: '波特兰开拓者 (Portland Trailblazers)',
  abbreviation: '开拓者',
  city: '俄勒冈州 波特兰市',
  latlng: '45.531437, -122.666714',
  side: '西部联盟',
  division: '西北赛区',
  arena: '摩达中心（Moda Center）',
}, {
  name: '·犹他爵士 (Utah Jazz)',
  abbreviation: '爵士',
  city: '犹他州 盐湖城',
  latlng: '40.768317, -111.900551',
  side: '西部联盟',
  division: '西北赛区',
  arena: '能量解决中心球馆(Delta Center)',
}, {
  name: '菲尼克斯太阳 (Phoenix Suns)',
  abbreviation: '太阳',
  city: '亚利桑纳州 菲尼克斯市',
  latlng: '33.445620, -112.071072',
  side: '西部联盟',
  division: '太平洋赛区',
  arena: '托金斯迪克度假酒店球馆(Talking Stick Resort Arena)',
}, {
  name: '萨克拉门托国王 (Sacramento Kings)',
  abbreviation: '国王',
  city: '加利福尼亚州 萨克拉门托市',
  latlng: '38.580120, -121.499589',
  side: '西部联盟',
  division: '太平洋赛区',
  arena: '黄金一号球馆（Golden 1 Center）',
}, {
  name: '洛杉矶快船 (L.A. Clippers)',
  abbreviation: '快船',
  city: '加利福尼亚州 洛杉矶市',
  latlng: '34.071859, -118.241937',
  side: '西部联盟',
  division: '太平洋赛区',
  arena: '斯台普斯球馆(STAPLES Center)',
}, {
  name: '洛杉矶湖人 (L.A. Lakers)',
  abbreviation: '湖人',
  city: '加利福尼亚州 洛杉矶市',
  latlng: '34.043000, -118.267050',
  side: '西部联盟',
  division: '太平洋赛区',
  arena: '斯台普斯球馆(STAPLES Center)',
}, {
  name: '金州勇士 (Golden State)',
  abbreviation: '勇士',
  city: '加利福尼亚州 奥克兰市',
  latlng: '37.750099, -122.203132',
  side: '西部联盟',
  division: '太平洋赛区',
  arena: '甲骨文球馆(Oracle Arena)',
}, {
  name: '圣安东尼奥马刺 (San Antonio Spurs)',
  abbreviation: '马刺',
  city: '德克萨斯州 圣安东尼奥市',
  latlng: '29.426904, -98.437262',
  side: '西部联盟',
  division: '西南赛区',
  arena: 'at&t中心球馆(AT&T Center)',
}, {
  name: '达拉斯独行侠 (Dallas Mavericks)',
  abbreviation: '独行侠',
  city: '得克萨斯州 达拉斯市',
  latlng: '32.790533, -96.810033',
  side: '西部联盟',
  division: '西南赛区',
  arena: '美国航线中心体育馆(American Airlines Center)',
}, {
  name: '休斯顿火箭 (Houston Rockets)',
  abbreviation: '火箭',
  city: '德克萨斯州 休斯顿市',
  latlng: '29.750509, -95.361875',
  side: '西部联盟',
  division: '西南赛区',
  arena: '丰田中心球馆(Toyota Center)',
}, {
  name: '孟菲斯灰熊 (Memphis Grizzlies)',
  abbreviation: '灰熊',
  city: '田纳西州 孟菲斯市',
  latlng: '35.138072, -90.050334',
  side: '西部联盟',
  division: '西南赛区',
  arena: '联邦快递体育馆(FedExForum)',
}, {
  name: '新奥尔良鹈鹕',
  abbreviation: '鹈鹕',
  city: '路易斯安那州 新奥尔良市',
  latlng: '29.948961, -90.082250',
  side: '西部联盟',
  division: '西南赛区',
  arena: '冰沙王中心(Smoothie King Center)',
}]